# Guess the random number

import random

question_1 = int(input("please guess your number? "))
generator = random.randint(0, question_1)   # this generates the random number

# Now guess the random number

while True:
    enter_num = int(input(f"guess the random number between 0 and {question_1}: "))   # here guess the number that was generated by the function above
    if enter_num == generator:
        print("You got it")
        break
    elif enter_num < generator:
        print("The number you entered is less than generated number")
    
    elif enter_num > generator:
        print("The number you entered is more than generated number")
    
    continue



